#! -------------------------------------------------------------------------
#! Mock-Travis Settings
#! -------------------------------------------------------------------------

mock_travis:
  # Set a particular test configuration for mock.
  mock_config: fedora-24-x86_64

  # Use RPM spec files from a GitHub repository
  # to generate extra part of buildrequires packages.
  # For example
  #         If your spec repository is 
  #         "https://github.com/nrechn/Sway-Fedora",
  #         git could be set to `nrechn/Sway-Fedora`
  packages_buildrequires_git: 
	UnitedRPMs/chromium-freeworld
  # Use extra/external repository during building packages.
  # This option allows mock to access an additional repository
  # plus defaults repositories based on the mock config.
  # gpgcheck is disabled in this option.
  # For example
  #         If add FZUG as an extra repository
  #         packages_extra_repo should set to
  #         "https://repo.fdzh.org/FZUG/testing/24/x86_64/"
  packages_extra_repo:
	https://sourceforge.net/projects/unitedrpms/files/25/x86_64/

#! -------------------------------------------------------------------------
#! DO NOT EDIT THE FOLLOWING SETTINGS
#! UNLESS YOU KNOW WHAT YOU ARE DOING
#! -------------------------------------------------------------------------

sudo: required

services:
  - docker

script:
  - wget -q https://github.com/nrechn/mock-travis/releases/download/latest/mock-travis 
        && chmod +x mock-travis 
        && ./mock-travis

