mock_travis:
  mock_config: fedora-25-x86_64
  packages_buildrequires_git: UnitedRPMs/chromium-freeworld
sudo: required
services:
  - docker
script:
  - wget -q https://github.com/paulcarroty/mock-travis/releases/download/stable/mock-travis 
    && chmod +x mock-travis 
    && ./mock-travis

notifications:
  slack: unitedrpms:lzDykHTpajKrgmGz9NkrO1Hj
