#! /bin/bash


# Put here the name of project used in copr
PROJECT_CHROMIUM=post-rpms
#

# Put here your user name copr
user_name=davidva

# Fedora version
rl=25

if [ -d $HOME/chromium-freeworld ]; then 
pushd $HOME/chromium-freeworld
git fetch origin master
git pull
elif [ -d $HOME/UnitedRPMs/chromium-freeworld/ ]; then 
pushd $HOME/UnitedRPMs/chromium-freeworld/
git fetch origin master
git pull
else 
cd $HOME
git clone https://github.com/UnitedRPMs/chromium-freeworld.git
pushd $HOME/chromium-freeworld
fi

wait ${!}

TARGET=$(wget -qO- https://omahaproxy.appspot.com/all | grep -e "linux,stable," -e releasestargets | cut -d, -f3)

wait ${!}

SPECV=$(cat chromium.spec | grep "Version:" | awk '{ print $NF }')

# Filter
if [ $TARGET = $SPECV ]; then
echo -e "\e[31mNo updates found...\e[0m"
exit
else
echo -e "\e[31mUpdates found...\e[0m"
fi
#

SVER=$( sed -n '/Version:/=' chromium.spec)
SRE=$( sed -n '/Release:/=' chromium.spec)

sed -i "${SVER}s/.*/Version:	$TARGET/" chromium.spec

rele=$(cat chromium.spec | grep "Release:" | awk '{ print $NF }' | grep -o '[0-9]*')

increrele=$(($rele+1))


dt=$(export LC_ALL=C && date "+%a %b %d %Y")

echo "* $dt David Vasquez <davidjeremias82 AT gmail DOT com>  $TARGET-$increrele
- Updated to $TARGET" > changdata.txt

f1="$(<changdata.txt)"

awk -vf1="$f1" '/%changelog/{print;print f1;next}1' chromium.spec | tee chromium2.spec

mv -f chromium2.spec chromium.spec

sed -i "${SRE}s/.*/Release:	$increrele%{?dist}/" chromium.spec

wait ${!}

#----------------------------------------------------
# SRPM TASK
# In order to access the restricted parts of the API, you will need to provide an API token. This token is unique, specific to you and should not be 
# shared!.
# The API token is valid for 180 days after it has been generated.
# You need to be logged in to see your API token.
# https://copr.fedorainfracloud.org/api/
#----------------------------------------------------

# rpmbuild -bs chromium.spec --define "_sourcedir $PWD" --buildroot $PWD
# rpmbuild --define "_topdir `pwd`" --define "_sourcedir $PWD"  -bs $PWD/chromium.spec

motherpath=/home/URPMS/$rl/srpm/

if [ -f "$motherpath/chromium-$SVER-$increrele.fc*.src.rpm" ] || [ -f "$HOME/enjoy$rl/srpm/chromium-$SVER-$increrele.fc*.src.rpm" ]; then 
echo 'Update no replace the current rpm'
exit
else
echo -e "\e[31mWe will make a srpm for you wait...\e[0m"
rpmbuild --define "_topdir /tmp/" --define "_sourcedir $PWD" -bs $PWD/chromium.spec
wait ${!}
copr-cli build $PROJECT_CHROMIUM /tmp/SRPMS/chromium-$TARGET-$increrele.fc*.src.rpm
fi

wait ${!}

# Dowload build id process

echo -e "\e[31mFind id builds\e[0m"

while sleep 12h
do
idbuild=$(curl -s https://copr.fedorainfracloud.org/coprs/$user_name/$PROJECT_CHROMIUM/builds/ | grep "$PROJECT_CHROMIUM/build/" | awk -F 'build/' '{print $2}' | awk -F '/">' '{print $1}' | sort | tail -1)

srpmver=$(curl -s https://copr.fedorainfracloud.org/coprs/$user_name/$PROJECT_CHROMIUM/build/$idbuild/ | grep ".src.rpm" | awk -F "chromium-" '{print $2}' | awk -F ".fc" '{print $1}')

echo -e "\e[31mDownloading built packages for you... in /tmp\e[0m"

copr-cli download-build $idbuild -d /tmp/
exit
done

# sort process
pushd /tmp/
ls -d fedora* | sed 's:/::g' | tee distro_directories.txt

file=distro_directories.txt
while IFS= read -r line; do
pushd /tmp/$line/
    mv -f *.rpm /tmp/ 
popd  
done <"$file"

popd  

echo -e "\e[31mSync process\e[0m"
pushd /home/URPMS/$rl/

add_packages.sh -a

wait ${!}

add_packages.sh -b

