version: 2
jobs:
  build:
    docker: 
      - image: davidva/unibuild-32
    working_directory: ~/enjoy
    no_output_timeout: 40m
    parallelism: 4
    steps:
      - checkout
      - run: " cd / && rm -f /urpms && /usr/bin/wget -c https://raw.githubusercontent.com/kuboosoft/united-build/master/urpms && chmod a+x $PWD/urpms && ./urpms -g UnitedRPMs/chromium-freeworld -s chromium-freeworld.spec -r true -d 'dist .fc32' -u true" 
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
notify:
  webhooks:
    # A list of hook hashes, containing the url field
    # gitter hook
    - url: https://webhooks.gitter.im/e/8ff0b35066468a87de71

        


